### ISSUE TITLE
AttributeError: 'pysam.calignmentfile.PileupRead' object has no attribute 'qpos'

### ISSUE THREAD

**Issue by mjafin** [uci-cbcl/PyLOH#2]
Hi There,
Thanks for releasing PyLOH as an open source package. I'm trying to run it for my data (hg19 aligned BAM files) but am getting the following error:
```
Loading segments by 22 autosomes...
Preprocessing segment chr1_start_0_end_249250621...
Preprocessing segment chr2_start_0_end_243199373...
Preprocessing segment chr3_start_0_end_198022430...
Preprocessing segment chr4_start_0_end_191154276...
Preprocessing segment chr5_start_0_end_180915260...
Preprocessing segment chr6_start_0_end_171115067...
Preprocessing segment chr7_start_0_end_159138663...
Preprocessing segment chr8_start_0_end_146364022...
Preprocessing segment chr9_start_0_end_141213431...
Preprocessing segment chr10_start_0_end_135534747...
Traceback (most recent call last):
  File "/home/klrl262/miniconda/envs/bcbio-test/bin/PyLOH.py", line 110, in <module>
    args.func(args)
  File "/home/klrl262/miniconda/envs/bcbio-test/lib/python2.7/site-packages/pyloh/preprocess/run_preprocess.py", line 51, in run_preprocess
Preprocessing segment chr11_start_0_end_135006516...
    converter.convert()
  File "/home/klrl262/miniconda/envs/bcbio-test/lib/python2.7/site-packages/pyloh/preprocess/run_preprocess.py", line 98, in convert
    counts_tuple_list = pool.map(process_by_segment, args_list)
  File "/home/klrl262/miniconda/envs/bcbio-test/lib/python2.7/multiprocessing/pool.py", line 251, in map
Preprocessing segment chr12_start_0_end_133851895...
    return self.map_async(func, iterable, chunksize).get()
  File "/home/klrl262/miniconda/envs/bcbio-test/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
AttributeError: 'pysam.calignmentfile.PileupRead' object has no attribute 'qpos'
```
Any ideas what this could be caused by?

**Comment by yil8** [comment]
Hi,

Thanks for your interest in using PyLOH. Could you show me the command line you used that caused this error? And also, is your data whole genome sequencing or whole exome sequencing?

Thanks

**Comment by mjafin** [comment]
Hi Yi,
I used the following command:
```
PyLOH.py preprocess /ngs/reference_data/genomes/Hsapiens/hg19/seq/hg19.fa /ngs/oncology/analysis/external/CCLE/HCC1954/downsampling_exercise/HCC1954/final/HCC1954BL/HCC1954BL-ready.bam /ngs/oncology/analysis/external/CCLE/HCC1954/downsampling_exercise/HCC1954/final/HCC1954/HCC1954-ready.bam HCC1954 --min_depth 20 --min_base_qual 10 --min_map_qual 10 --process_num 10
```
This is WGS data.

**Comment by yil8** [comment]
Thanks for the additional information.

I probably found out the reason. What is the version of pysam you are using? I just found out pysam was developed again on github after its last release on google code as 0.7.5. since 2013. And unfortunately in their latest release, they rename the 'qpos' property  as 'query_position' causing backward incompatible:
https://github.com/pysam-developers/pysam/issues/68

So, I would suggest using pysam-0.7x that you can find at:
https://code.google.com/p/pysam/

In theory, I could also update my code to follow their change, but that probably will cause the old PyLOH users annoyed. Sorry!

Thanks

**Comment by mjafin** [comment]
Thanks for looking into this Yi, much appreciated! I indeed do use one of the more recent versions of pysam. I wonder if you could check in the code if one or the other (``qpos`` or ``query_position``) exists and roll with that? Wouldn't break anything. I recall other properties got renamed too btw. but I don't have a list.

**Comment by yil8** [comment]
That's a good suggestion. But as you said some other property may also be renamed. I need to install the latest pysam on my machine and do a systematical check which may take some time.  But thanks for pointing out!

**Comment by yil8** [comment]
issue resolved：
https://github.com/uci-cbcl/PyLOH/releases/tag/1.4.1

**Comment by mjafin** [comment]
Thanks I'll give it a go!
