### ISSUE TITLE
pyLOH slow preprocessing?

### ISSUE THREAD

**Issue by lonestar21** [uci-cbcl/PyLOH#5]
Hi.
I recently heard about your tool and decided to give it a try.

I'm trying to run it on a 100X tumour and 100X normal pair that have been aligned with BWA mem.

It has been running for 60 hours now, but I still don't see any output files and the message to the screen still says:
> Loading segments by 22 autosomes...
> Preprocessing segment 1_start_0_end_249250621...

The python process is still running in my machine suggesting something is still running under the hood.

Do you have any suggestions of anything that might be going wrong?   I'm using a machine with 64Gb of RAM that is otherwise running expectedly fast.

**Comment by yil8** [comment]
Hi,

Most likely I'm guessing you are using pysam0.8x? For some unknown reasons, there seems to be a big change from pysam0.7x to pysam0.8x, and pysam0.8x just works significantly slower than pysam0.7x practically. I've retested both pysam0.7.5 and pysam0.8.4 to preprocess the example data (of 10 segments) with 5 cores Intel i7. pysam0.7.5 took ~4 hours while pysam0.8.4 took ~17 hours. So, I would recommend switching back to pysam0.7x , if it does not cause you too much trouble

Also, it seems like you are using single core, as only one chromosome got processed? I highly recommend using multicore to do the preprocessing if you have more than one CPU. That will also reduce the processing time significantly.

Thanks
