### ISSUE TITLE
Puzzled in tumor ploidy

### ISSUE THREAD

**Issue by QqQss** [uci-cbcl/PyLOH#7]
Hi, I'm a new-come researcher in cancer DNA sequencing.  And I have some problems about the concept of tumor ploidy. 
The puzzle mainly focus on "--allelenumber_max" parameter and "Optimum baseline copy number" value in output .PyLOH.purity file.

1) In the default setting and example command, the "--allelenumber_max" you chosen is 2. But we all known that tumor cells frequently  occur DNA segment amplification or chromosome duplication, so the allele number may increase and will be more than 2. Besides, I tried to use some different number (5, 10) to rerun program for the same inputs, and found the result "Tumor purit" and "Optimum baseline copy number" get different numbers.  So, which result should be accepted? and how do I setting the "--allelenumber_max" value?

2) Is the "Optimum baseline copy number" number from your software result equivalent to the "ploidy" number from other analogous software result, like ABSOLUTE and ASCAT?

**Comment by yil8** [comment]
Hi, @QqQss 

Thanks for using PyLOH. For your questions:

1. Yes you are right. By default, the max allowed allele number for each chromosome is 2, which means the max copy number allowed is 4. Therefore, when we evaluating all the possible allele number combinations and their corresponding likelihood scores, we only consider cases where the allele number of each chromosome is maximally 2. If you are using higher max allele numbers, then there are more potential allele number combinations for evaluations, and may indeed get different results. However, higher allele number combinations requires deeper sequencing depth for statistical significances, (imagine max allele number is 10, then the counts differences between 9:11 vs 10:10 requires very large coverage and read counts to show statistical significant differences.) So, the algorithm probably won't get reliable results if it is allowed to consider these complex possibilities. In a nutshell, if you just want to estimate tumor purity, then 1 copy deletion and 1 copy duplication is usually the most reliable signal in the read counts information for such calculation.

2. I'm not that familiar with ABSOLUTE and ASCAT, but it sounds correct that baseline copy number in PyLOH is equivalent to ploidy in ABSOLUTE and ASCAT.
