### ISSUE TITLE
Error: No diploid segments found, existing...

### ISSUE THREAD

**Issue by harshmishah** [uci-cbcl/PyLOH#8]
Hi, 
I got "Error: No diploid segments found, existing..." when running the run_model command. I've run it on few samples and they run perfectly but some samples give this error. 
PS. I did see a similar closed issue but I don't see if/how this was solved in that case.
Thank you!

**Comment by yil8** [comment]
@harshmishah Hi, it's not solved in that case...it usually means there is not enough normal SNPs within the data to set the baseline.
